### PR TITLE
Release Build

### PR DESCRIPTION
**Pull request by JamesG9802**
Implements APS algorithm on arduino system (Arduino Nano 33 IoT).
Implements fake CGM communication to read blood glucose from the user.
Implements APS system integration with Insulin pump to deliver dosages accordingly.

### CODE REVIEW

**Review by mishlosh — COMMENTED** [review]
I'm a bit confused in MyProject2/Buttons.c
Each time there is a button interrupt, I believe it loads up button_array[0] from flash memory so that data is preserved. But I don't think insulinDeliveryIndex is, I think it is perpetually reset to -1. I don't think this creates an issue unless we send a number larger than 8 bits.

Also, if it writes the 1 or 0, then bitshifts to the left, it's reading the number left-to-right, but SendNumberToPump() in Arduino/aps.ino is commented to send the number right-to-left?

**Comment by JamesG9802** [comment]
Also, I see your concern with insulinDeliveryIndex not being stored in flash memory. While it should not be a problem since the pump has its ability to reset periodically removed, we can implement that for safety.

**Comment by arlarv** [comment]
Just to clarify, we're under the assumption that the implemented APS system is receiving user info from a user-provided CGM right? Is there a need to vet/sanitize incoming user data?

**Review by mishlosh — APPROVED** [review]
I think the issues with insulinDeliveryAmount and insulinDeliveryIndex are resolved.

**Pull request merged**
